name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore oop-s3-1-mvc-83303.slnx
    - name: Build
      run: dotnet build oop-s3-1-mvc-83303.slnx --no-restore
    - name: Test
      run: dotnet test oop-s3-1-mvc-83303.slnx --no-build --verbosity normal
